import { NavBar } from "~/components/layout/Navbar";
import { type AppType } from "next/dist/shared/lib/utils";
import "~/styles/globals.css";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return(
    <>
      <Head>
        <title>Pradeep Rao K</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Component {...pageProps} />
    </>
  );
   
};

export default MyApp;
