/* eslint-disable react/no-unescaped-entities */
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pradeep Rao K</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="fade flex justify-center items-center flex-col h-full pb-20">
        <h1 className="text-6xl mb-2">
          👋, I'm <span className="text-purple-300">Pradeep Rao K</span>.
        </h1>
        <h2 className="text-4xl w-4/5 md:w-1/3 2xl:w-1/6 text-center">
          Developer who likes to build things.
        </h2>
      </div>

    </>
  );
};

export default Home;
